version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  front-end:
    container_name: front-end
    build:
      context: client/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
    environment:
      - NODE_ENV=development
